var arrLang = {
  "en": {
    "accedi": "Sign in",
    "registrati": "Sign up!",
    'slogan': 'Say goodbye to waste',
    'home': 'Home', 
    'profilo': 'Profile',
    'statistiche': 'Analytics',
    'lista spesa': 'Shopping list',
    'dispense': 'Your pantries',
    'invia' : 'Submit',
    'nome' : 'Name',
    'cognome': 'Surname',
    'account': "Don't have an account?",
    'register': 'Register',
    'header': "Foodmate allows you to manage your pantry in a smart way, so you don't have to throw away food anymore",
    'letsgo': "Let's go!",
    'logout': 'Exit',
    'nome_pro': 'Name:',
    'cognome_pro': 'Surname:',
    'sesso_pro':  'Gender:',
    'email_pro': 'Email:',
    'psw_pro': 'Password:',
    'ricette': 'Recipes',
    'logout':'Logout',
    'no_ricette':'There are no recipes to show',
    'colazione': 'Breakfast',
    'primo': 'First course',
    'secondo': 'Second course',
    'snack': 'Snack',
    'dessert': 'Dessert',
    'macedonia_title':'Fruit salad',
    'macedonia_desc':'Summer is when the fruit salad becomes your best friend, with its sweetness and freshness that refresh you on hot summer days.',
    'vellutata di verdure_title':'Vegetable soup',
    'vellutata di verdure_desc':'The vegetable soup is a creamy and delicate first course, perfect for cold winter days.',
    'paella_title':'Paella',
    'paella_desc':'The paella is a typical Spanish dish, based on rice and fish, which is prepared in a large pan.',
    'spiedini_title':'Meat skewers',
    'spiedini_desc':'The meat skewers are a very tasty and easy to prepare second course, perfect for a dinner with friends.',
    'torta di mele_title':'Apple pie',
    'torta di mele_desc':'The apple pie is a simple and genuine dessert, perfect for breakfast or a snack.',
    'ravioli_title':'Chinese ravioli',
    'ravioli_desc':'Chinese ravioli are a typical Chinese dish, made with pasta stuffed with meat or vegetables.',
    'qty': 'Qty',
    'scadenza': 'Exp',
    'email': 'Email',
    'password': 'Password',
    'sesso': 'Gender',
    'newDispensa': 'New pantry',
    'Nome': 'Name',
    'close': 'Close',
    'provvista': 'New supply',
    'nome_prov': 'Name:',
    'exp': 'Expiration date',
    'quantita': 'Quantity',
    'type': 'Type:',
    'menu': 'Open this select menu',
    'elimina': 'Delete',
    'add': 'Add',
    'carne': 'Meat',
    'verdura': 'Vegetable',
    'frutta': 'Fruit',
    'cereali': 'Cereals',
    'pesce': 'Fish',
    'dolce': 'Dessert',
    'latticini': 'Dairy',
    'altro': 'Other',
    'Gennaio': 'January',
    'Febbraio': 'February',
    'Marzo': 'March',
    'Aprile': 'April',
    'Maggio': 'May',
    'Giugno': 'June',
    'Luglio': 'July',
    'Agosto': 'August',
    'Settembre': 'September',
    'Ottobre': 'October',
    'Novembre': 'November',
    'Dicembre': 'December',
    'suggerimenti_title': 'It seems that these foods are about to run out, what about adding them to the shopping list?',
    'ne_hai': 'You have',
    'scaduti': 'expired',
    'scadenza prossima': 'next expiration',
    'ottimo stato': 'great condition',
    'monitoraggio_intelligente':'Keeping your pantry under control is good for the Earth and your wallet!',
    'monitoraggio_intelligente_title':'Smart monitoring',
    'multilingue':'Foodmate is multilingual, you can choose the language you prefer!',
    'multilingue_title':'Multilingual',
    'open_source':'The code of Foodmate is entirely consultable on GitHub!',
    'open_source_title':'Open Source',
    'user_friendly':'Foodmate is easy to use and intuitive!',
    'user_friendly_title':'User Friendly',
    'eliminaDispensa': 'Delete pantry',
    'img': 'Image',
    'psw_att' : 'Current password',
    'psw_new' : 'New password',
    'nome_new' : 'New name',
    'cognome_new' : 'New surname',
  },

  "it": {
    "accedi": "Accedi",
    "registrati": "Registrati!",
    "slogan" : 'Dì addio allo spreco',
    'home': 'Home',
    'profilo': 'Profilo',
    'statistiche': 'Statistiche',
    'lista spesa': 'Lista della spesa',
    'dispense': 'Le tue dispense',
    'invia': 'Invia',
    'nome': 'Nome',
    'cognome': 'Cognome',
    'account': 'Non hai un account?',
    'register': 'Registrati',
    'header': 'Foodmate ti permette di gestire la tua dispensa in modo intelligente, cosi da non dover più buttare cibo',
    'letsgo': "Iniziamo!",
    'logout': 'Esci',
    'nome_pro': 'Nome:',
    'cognome_pro': 'Cognome:',
    'sesso_pro': 'Sesso:',
    'email_pro': 'Email:',
    'psw_pro': 'Password:',
    'ricette': 'Ricette',
    'logout':'Esci',
    'no_ricette':'Non ci sono ricette da mostrare',
    'colazione': 'Colazione',
    'primo': 'Primo',
    'secondo': 'Secondo',
    'snack': 'Snack',
    'dessert': 'Dolce',
    'macedonia_title':'Macedonia di frutta',
    'macedonia_desc':'Estate è quando la macedonia di frutta diventa la tua migliore amica,con la sua dolcezza e freschezza che ti rinfrescano nelle calde giornate estive.',
    'vellutata di verdure_title':'Vellutata di verdure',
    'vellutata di verdure_desc':'La vellutata di verdure è un primo piatto cremoso e delicato, perfetto per le giornate fredde invernali.',
    'paella_title':'Paella',
    'paella_desc':'La paella è un piatto tipico spagnolo, a base di riso e pesce, che viene preparato in una grande padella.',
    'spiedini_title':'Spiedini di carne',
    'spiedini_desc':'Gli spiedini di carne sono un secondo piatto molto gustoso e semplice da preparare, perfetto per una cena tra amici.',
    'torta di mele_title':'Torta di mele',
    'torta di mele_desc':'La torta di mele è un dolce semplice e genuino, perfetto per la colazione o la merenda',
    'ravioli_title':'Ravioli Cinesi',
    'ravioli_desc':'I ravioli cinesi sono un piatto tipico della cucina cinese, a base di pasta ripiena di carne o verdure.',
    'qty': 'Qta',
    'scadenza': 'Scad',
    'email': 'Email',
    'password': 'Password',
    'sesso': 'Sesso',
    'newDispensa': 'Nuova Dispensa',
    'Nome': 'Nome',
    'close': 'Chiudi',
    'provvista': 'Nuova Provvista',
    'nome_prov': 'Nome:',
    'exp': 'Data di scadenza:',
    'quantita': 'Quantità',
    'type': 'Tipo',
    'menu': 'Apri questo menu a tendina',
    'elimina': 'Elimina',
    'add': 'Aggiungi',
    'carne': 'Carne',
    'verdura': 'Verdura',
    'frutta': 'Frutta',
    'cereali': 'Cereali',
    'pesce': 'Pesce',
    'dolce': 'Dolce',
    'latticini': 'Latticini',
    'altro': 'Altro',
    'Gennaio': 'Gennaio',
    'Febbraio': 'Febbraio',
    'Marzo': 'Marzo',
    'Aprile': 'Aprile',
    'Maggio': 'Maggio',
    'Giugno': 'Giugno',
    'Luglio': 'Luglio',
    'Agosto': 'Agosto',
    'Settembre': 'Settembre',
    'Ottobre': 'Ottobre',
    'Novembre': 'Novembre',
    'Dicembre': 'Dicembre',
    'suggerimenti_title': 'Sembra che questi alimenti stiano per finire,che ne dici di aggiungerli alla lista della spesa?',
    'ne_hai': 'Ne hai',
    'scaduti': 'scaduti',
    'scadenza prossima': 'scadenza prossima',
    'ottimo stato': 'ottimo stato',
    'monitoraggio_intelligente':'Tenere sotto controllo le tue dispense fa bene alla Terra e al tuo portafoglio!',
    'monitoraggio_intelligente_title':'Monitoraggio intelligente',
    'multilingue':'Foodmate è multilingue, puoi scegliere la lingua che preferisci!',
    'multilingue_title':'Multilingue',
    'open_source':'Il codice di Foodmate è interamente consultabile su GitHub!',
    'open_source_title':'Open Source',
    'user_friendly':'Foodmate è facile da usare e intuitivo!',
    'user_friendly_title':'User Friendly',
    'eliminaDispensa': 'Elimina dispensa',
    'img': 'Immagine',
    'pws_att': 'Password attuale',
    'pws_new': 'Nuova password',
    'nome_new': 'Nuovo nome',
    'cognome_new': 'Nuovo cognome',
  },

  "cn": {
    "accedi": "登录",
    "registrati": "注册",
    'slogan': '对浪费说再见',
    'home': '主页', 
    'profilo': '个人信息',
    'statistiche': '统计数据',
    'lista spesa': '购物清单',
    'dispense': '您的食品储藏室',
    'invia' : '提交',
    'nome' : '名',
    'cognome': '姓',
    'account': "没有账户？",
    'register': '注册',
    'header': "Foodmate可以智能地管理您的食品储藏室，因此您不必再扔掉食物了。",
    'letsgo': "开始吧！",
    'logout': '退出',
    'nome_pro': '名:',
    'cognome_pro': '姓:',
    'sesso_pro':  '性别:',
    'email_pro': '邮箱:',
    'psw_pro': '密码:',
    'ricette': '食谱',
    'colazione': '早餐',
    'pranzo': '午餐',
    'cena': '晚餐',
    'snack': '零食',
    'macedonia_title':'水果沙拉',
    'macedonia_desc':'夏天是水果沙拉成为您最好的朋友的时候，它的甜美和清新可以在炎热的夏日为您带来清凉。',
    'vellutata di verdure_title':'蔬菜汤',
    'vellutata di verdure_desc':'蔬菜汤是一道奶油味浓郁的头盘，非常适合寒冷的冬天。',
    'paella_title':'西班牙海鲜饭',
    'paella_desc':'西班牙海鲜饭是一道典型的西班牙菜，以米饭和鱼为主料，在大锅中烹制而成。',
    'email': '邮箱',
    'password': '密码',
    'sesso': '性别',
    'newDispensa': '新食品储藏室',
    'Nome': '名字',
    'close': '关闭',
    'provvista': '新供应',
    'nome_prov': '食品名',
    'exp': '有效期',
    'quantita': '数量',
    'type': '类型',
    'menu': '打开下拉菜单',
    'elimina': '删除',
    'add': '添加',
    'ravioli_title':'中国饺子',
    'ravioli_desc':'中国饺子是中国的一道典型菜肴，用肉或蔬菜做馅，用面皮包裹而成。',
    'qty': '数量',
    'scadenza': '有效期',
    'frutta': '水果',
    'verdura': '蔬菜',
    'carne': '肉',
    'cereali': '谷物',
    'pesce': '鱼',
    'dolce': '甜点',
    'latticini': '乳制品',
    'altro': '其他',
    'Gennaio': '一月',
    'Febbraio': '二月',
    'Marzo': '三月',
    'Aprile': '四月',
    'Maggio': '五月',
    'Giugno': '六月',
    'Luglio': '七月',
    'Agosto': '八月',
    'Settembre': '九月',
    'Ottobre': '十月',
    'Novembre': '十一月',
    'Dicembre': '十二月',
    'suggerimenti_title': '这些食物似乎快要用完了，把它们加到购物清单上怎么样？',
    'ne_hai': '你有',
    'scaduti': '过期',
    'scadenza prossima': '即将过期',
    'ottimo stato': '良好状态',
    'monitoraggio_intelligente':'控制您的食品储藏室对地球和您的钱包都有好处！',
    'monitoraggio_intelligente_title':'智能监控',
    'multilingue':'Foodmate是多语言的，您可以选择您喜欢的语言！',
    'multilingue_title':'多语言',
    'open_source':'Foodmate的代码完全可以在GitHub上查看！',
    'open_source_title':'开源',
    'user_friendly':'Foodmate易于使用且直观！',
    'user_friendly_title':'用户友好',
    'eliminaDispensa': '删除食品储藏室',
    'img': '图片',
    'psw_att': '当前密码',
    'psw_new': '新密码',
    'nome_new': '新名字',
    'cognome_new': '新姓氏',
  },
};


var lang = "en";
// Check for localStorage support
if ('localStorage' in window) {
  var usrLang = localStorage.getItem('uiLang');
  if (usrLang) {
    lang = usrLang;
  }
}

$(document).ready(function() {
  $(".lang").each(function(index, element) {
    $(this).append(arrLang[lang][$(this).attr("key")])
  });

  $(".langSidebar .link-text").each(function() {
    var key = $(this).parent().attr("key");
    $(this).text(arrLang[lang][key]);
  });
});

// get/set the selected language
$(".translate").click(function() {
  var lang = $(this).attr("id");

  // update localStorage key
  if ('localStorage' in window) {
    localStorage.setItem('uiLang', lang);
    console.log(localStorage.getItem('uiLang'));
  }

  $(".lang").each(function(index, element) {
    $(this).text(arrLang[lang][$(this).attr("key")]);
  });

  $(".langSidebar .link-text").each(function() {
    var key = $(this).parent().attr("key");
    $(this).text(arrLang[lang][key]);
  });
});


function translate(key) {
  return arrLang[lang][key];
}


